---
apiVersion: v1
kind: ConfigMap

metadata:
    name: chatbot-env

data:
    PORT: "5000"
    BUILD_INFO_PATH: /app/build-info.json
    MANAGER_URL: http://manager.foreman.svc.cluster.local:5001
    RASA_URL: http://rasa.foreman.svc.cluster.local:8080
