---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
    name: chatbot

spec:
    minAvailable: 1
    selector:
        matchLabels:
            app: chatbot
            version: v1
            platform: foreman
