---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-web-auth

spec:
    externalSecretName: web-auth

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: "1h"
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: web-auth
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: Auth0

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-web-misc

spec:
    externalSecretName: web-misc

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: web-misc
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/library/web/misc

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-web-cache

spec:
    externalSecretName: web-cache

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: web-cache
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/support/cache/client

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-web-files

spec:
    externalSecretName: web-files

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: web-files
            creationPolicy: Owner
            template:
                type: Opaque
                data:
                    newrelic.ini: "{{ .contents | toString }}"
        data:
            - secretKey: contents
              remoteRef:
                  key: NewRelic

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-template-credentials

spec:
    externalSecretName: template-credentials

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: template-credentials
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: TemplateRepo
