---
apiVersion: v1
kind: ConfigMap

metadata:
    name: chatbot-common

data:
    FLASK_PORT: "5000"
    FLASK_APP: foreman.main:create_app
    FLASK_ENV: production
    NEW_RELIC_CONFIG_FILE: /config/newrelic.ini
