---
kind: Service
apiVersion: v1

metadata:
    name: chatbot

spec:
    selector:
        app: chatbot
        version: v1
        platform: foreman
    type: LoadBalancer
    ports:
        - name: http
          port: 5000
          targetPort: http
