"""
constants.py
"""

SENTRY_DSN = "SENTRY_DSN"
SLACK_API_TOKEN = "SLACK_API_TOKEN"
MANAGER_URL = "MANAGER_URL"
MANAGER_AUTH_TOKEN = "MANAGER_AUTH_TOKEN"
RASA_URL = "RASA_URL"
RASA_AUTH_TOKEN = "RASA_AUTH_TOKEN"
